apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bet-solar-system
  name: beta-solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beta-solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: beta-solar-system
    spec:
      containers:
      - image: siddharth67/solar-system:v9
        name: solar-system
        imagePullPolicy: Always
        ports:
        - containerPort: 80
