apiVersion: v1
kind: Service
metadata:
  labels:
    app: bet-solar-system
  name: beta-solar-system-service
spec:
  selector:
    app: beta-solar-system
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
